<?php
use Icinga\Web\Widget\SearchDashboard;
?>
<? if (SearchDashboard::search('dummy')->getPane('search')->hasDashlets()): ?>
    <h1><?= t('Search'); ?></h1>
    <form action="<?= $this->href('search') ?>" method="get" role="search">
        <input
            type="text" name="q" class="search" placeholder="<?= $this->translate('Search...') ?>"
            autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"
        />
    </form>
<? endif; ?>
<h1><?= t('Local Navigation'); ?></h1>
<?= $menuRenderer; ?>
