<?php

use Icinga\Web\Url;
use Icinga\Web\Notification;
use Icinga\Authentication\Manager as Auth;
use Icinga\Web\Widget\SearchDashboard;


if (Auth::getInstance()->isAuthenticated()): ?>
 <div id="header">
   <ul id="notifications"><?php

$moduleName = $this->layout()->moduleName;
if ($moduleName) {
    $moduleClass = ' icinga-module module-' . $moduleName;
} else {
    $moduleClass = '';
}

$refresh = '';
if ($this->layout()->autorefreshInterval) {
    $refresh = ' data-icinga-refresh="' . $this->layout()->autorefreshInterval . '"';
}

$notifications = Notification::getInstance();
if ($notifications->hasMessages()) {
    foreach ($notifications->getMessages() as $m) {
        echo '<li class="' . $m->type . '">' . $this->escape($m->message) . '</li>';
    }
}
   ?></ul>
  <div id="logo" data-base-target="_main">
   <a href="<?= $this->href('/dashboard') ?>">
    <img src="<?= $this->href('img/logo_icinga-inv.png') ?>" class="logo" alt="<?= t('Dashboard') ?>" />
   </a>
  </div>
  <div id="skipcontent">
   <h1><?= t('Skip To Content Links'); ?></h1>
   <ul>
    <li><a href="#navigation"><?= t('Skip To Local Navigation'); ?></a></li>
    <?php if (SearchDashboard::search('dummy')->getPane('search')->hasDashlets()): ?>
      <li><a href="#search"><?= t('Skip To Search'); ?></a></li>
    <?php endif; ?>
    <li><a href="#main"><?= t('Skip To Main Content'); ?></a></li>
   </ul>
  </div>
 </div>

<?php if (!$this->layout()->isIframe): ?>
 <div id="sidebar">
  <?php echo $this->render('parts/navigation.phtml') ?>
 </div>
<?php endif ?>
 <div id="main" role="main">
  <h1 class="hidden-text"><a name="main">Main Content</a></h1>
  <div id="col1" class="container<?= $moduleClass ?>"<?php if ($moduleName): ?> data-icinga-module="<?= $moduleName ?>" <?php endif ?> data-icinga-url="<?= Url::fromRequest()->without('renderLayout') ?>"<?= $refresh ?> style="display: block">
   <?= $this->render('inline.phtml') ?>
  </div>
  <div id="col2" class="container">
  </div>
  <div id="col3" class="container">
  </div>
 </div><!-- END of main -->
<?php else: ?>
<?= $this->render('inline.phtml') ?>
<?php endif ?>
