<?php

use Icinga\Web\Url;
use Icinga\Web\Menu;
use Icinga\Web\MenuRenderer;
use Icinga\Web\Widget\SearchDashboard;

// Don't render a menu for unauthenticated users unless menu is auth aware
if (! $this->auth()->isAuthenticated()) {
    return;
}

?>
<div
    id="menu" data-last-update="<?= (time() - 14) ?>000" data-base-target="_main" class="container" data-icinga-url="<?=$this->href('layout/menu');?>"
    data-icinga-refresh="15"
>
  <? if (SearchDashboard::search('dummy')->getPane('search')->hasDashlets()): ?>
      <h1><a name="search"><?= t('Search'); ?></a></h1>
      <form action="<?= $this->href('search') ?>" method="get" role="search">
        <input type="text" name="q" class="search" placeholder="<?= $this->translate('Search...') ?>"
               autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" />
      </form>
  <? endif; ?>
  <h1><a name="navigation"><?= t('Local Navigation'); ?></a></h1>
  <?= new MenuRenderer(Menu::load(), Url::fromRequest()->without('renderLayout')->getRelativeUrl()); ?>
</div>
